package com.itson.equipo2.battleship_cliente.view;

import com.itson.equipo2.battleship_cliente.models.CeldaModel;
import com.itson.equipo2.battleship_cliente.models.JugadorModel;
import com.itson.equipo2.battleship_cliente.models.PartidaModel;
import com.itson.equipo2.battleship_cliente.models.TableroModel;
import com.itson.equipo2.battleship_cliente.pattern.factory.ViewFactory;
import com.itson.equipo2.battleship_cliente.pattern.mediator.GameMediator;
import com.itson.equipo2.battleship_cliente.controllers.ViewController;
import com.itson.equipo2.battleship_cliente.pattern.observer.PartidaObserver;
import com.itson.equipo2.battleship_cliente.pattern.observer.TableroObserver;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import mx.itson.equipo_2.common.dto.CoordenadaDTO;
import mx.itson.equipo_2.common.dto.DisparoDTO;
import mx.itson.equipo_2.common.enums.EstadoPartida;
import mx.itson.equipo_2.common.enums.ResultadoDisparo;

/**
 *
 * @author Ariel Eduardo Borbon Izaguirre 00000252116 Sebastián Bórquez Huerta
 * 00000252115 Alberto Jiménez García 00000252595 José Eduardo Aguilar García
 * 00000252049 José Luis Islas Molina 00000252574
 */
public class DispararView extends javax.swing.JPanel implements ViewFactory, TableroObserver, PartidaObserver {

    private JButton[][] botonesPropio = new JButton[10][10];
    private JButton[][] botonesEnemigo = new JButton[10][10];

    private CoordenadaDTO coordSeleccionada;
    private JButton ultimaSeleccionada;
    private Color colorOriginalUltima;

    private TableroModel miTablero;
    private TableroModel tableroEnemigo;

    private JugadorModel jugador;
    private GameMediator mediator;

    /**
     * Creates new form DispararView
     */
    public DispararView() {
        initComponents();
        crearCeldas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTableroEnemigo = new JPanel();
        btnRendirse = new JButton();
        btnDisparar = new JButton();
        panelTableroPropio = new JPanel();
        lblTimer = new JLabel();

        setBackground(new Color(83, 111, 137));
        setMaximumSize(new Dimension(1280, 720));
        setMinimumSize(new Dimension(1280, 720));
        setPreferredSize(new Dimension(1280, 720));
        setLayout(null);

        panelTableroEnemigo.setBackground(new Color(82, 113, 177));
        panelTableroEnemigo.setMaximumSize(new Dimension(600, 600));
        panelTableroEnemigo.setMinimumSize(new Dimension(600, 600));
        panelTableroEnemigo.setLayout(new GridLayout(1, 0));
        add(panelTableroEnemigo);
        panelTableroEnemigo.setBounds(615, 56, 600, 600);

        btnRendirse.setBackground(new Color(75, 75, 75));
        btnRendirse.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRendirse.setForeground(new Color(255, 255, 255));
        btnRendirse.setText("RENDIRSE");
        btnRendirse.setBorder(null);
        btnRendirse.setFocusPainted(false);
        btnRendirse.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRendirseActionPerformed(evt);
            }
        });
        add(btnRendirse);
        btnRendirse.setBounds(60, 650, 156, 41);

        btnDisparar.setBackground(new Color(75, 75, 75));
        btnDisparar.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDisparar.setForeground(new Color(255, 255, 255));
        btnDisparar.setText("DISPARAR");
        btnDisparar.setBorder(null);
        btnDisparar.setFocusPainted(false);
        btnDisparar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnDispararActionPerformed(evt);
            }
        });
        add(btnDisparar);
        btnDisparar.setBounds(260, 650, 156, 41);

        panelTableroPropio.setBackground(new Color(82, 113, 177));
        panelTableroPropio.setMaximumSize(new Dimension(250, 250));
        panelTableroPropio.setMinimumSize(new Dimension(250, 250));
        panelTableroPropio.setLayout(new GridLayout(10, 10));
        add(panelTableroPropio);
        panelTableroPropio.setBounds(130, 50, 250, 250);

        lblTimer.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        lblTimer.setText("...");
        add(lblTimer);
        lblTimer.setBounds(100, 320, 360, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRendirseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRendirseActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas rendirte?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            System.out.println("El jugador se rindió");
        }
    }//GEN-LAST:event_btnRendirseActionPerformed

    private void btnDispararActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDispararActionPerformed
        if (coordSeleccionada == null) {
            mostrarError("Debes seleccionar una casilla para disparar.");
            return;
        }
        if (mediator != null) {
            mediator.disparar(coordSeleccionada.getColumna(), coordSeleccionada.getFila());
            System.out.println("1");
        }
    }//GEN-LAST:event_btnDispararActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnDisparar;
    private JButton btnRendirse;
    private JLabel lblTimer;
    private JPanel panelTableroEnemigo;
    private JPanel panelTableroPropio;
    // End of variables declaration//GEN-END:variables

    private void crearCeldas() {
        botonesEnemigo = new JButton[10][10];
        botonesPropio = new JButton[10][10];

        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {

                JButton celdaEnemigo = new JButton();
                celdaEnemigo.setBackground(new Color(50, 70, 100));
                celdaEnemigo.setBorder(new LineBorder(Color.BLACK, 1));

                final int f = fila;
                final int c = col;

                celdaEnemigo.addActionListener(e -> {

                    if (ultimaSeleccionada != null) {
                        ultimaSeleccionada.setBorder(new LineBorder(Color.BLACK, 1));
                    }

                    ultimaSeleccionada = celdaEnemigo;

                    celdaEnemigo.setBorder(new LineBorder(Color.GRAY, 3));

                    coordSeleccionada = new CoordenadaDTO(f, c);
                });

                panelTableroEnemigo.add(celdaEnemigo);
                botonesEnemigo[fila][col] = celdaEnemigo;

                JButton celdaPropio = new JButton();
                celdaPropio.setEnabled(false);
                celdaPropio.setBackground(new Color(50, 70, 100));
                celdaPropio.setBorder(new LineBorder(Color.BLACK, 1));

                panelTableroPropio.add(celdaPropio);
                botonesPropio[fila][col] = celdaPropio;
            }
        }
    }

    public void actualizarCeldaEnemigo(DisparoDTO dto) {

        if (dto.getResultado() == ResultadoDisparo.IMPACTO_CON_HUNDIMIENTO) {

            for (CoordenadaDTO coord : dto.getCoordenadasBarcoHundido()) {
                JButton boton = botonesEnemigo[coord.getFila()][coord.getColumna()];
                boton.setBackground(Color.RED);
            }

        } else {

            CoordenadaDTO c = dto.getCoordenada();
            JButton boton = botonesEnemigo[c.getFila()][c.getColumna()];
            Color nuevoColor = switch (dto.getResultado()) {
                case AGUA ->
                    Color.BLUE;
                case IMPACTO_SIN_HUNDIMIENTO ->
                    Color.ORANGE;
                default ->
                    boton.getBackground(); //no deberia pasar pero pues por si acaso
            };
            boton.setBackground(nuevoColor);
        }
    }

    public void actualizarCeldaPropia(DisparoDTO dto) {

        if (dto.getResultado() == ResultadoDisparo.IMPACTO_CON_HUNDIMIENTO) {

            for (CoordenadaDTO coord : dto.getCoordenadasBarcoHundido()) {
                JButton boton = botonesPropio[coord.getFila()][coord.getColumna()];
                boton.setBackground(Color.BLACK);
            }

        } else {
            CoordenadaDTO c = dto.getCoordenada();
            JButton boton = botonesPropio[c.getFila()][c.getColumna()];
            switch (dto.getResultado()) {
                case AGUA ->
                    boton.setBackground(Color.CYAN);
                case IMPACTO_SIN_HUNDIMIENTO ->
                    boton.setBackground(Color.MAGENTA);
            }
        }
    }

    @Override
    public JPanel crear(ViewController control) {
        return this;
    }

    public void mostrarTableroPropio(TableroModel tablero) {
        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {
                CeldaModel celda = tablero.getCelda(fila, col);
                if (!celda.isTieneNave()) {
                    botonesPropio[fila][col].setBackground(Color.DARK_GRAY);
                }
            }
        }
    }

    public void actualizarTimer(int segundosRestantes, String jugador) {
        lblTimer.setText("Turno de " + jugador + " - Tiempo: " + segundosRestantes + "s");
    }

    public void setJugador(JugadorModel jugador) {
        this.jugador = jugador;
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.WARNING_MESSAGE);
    }

    @Override
    public void onDisparo(TableroModel tableroAfectado, DisparoDTO disparo) {

        if (tableroAfectado == this.tableroEnemigo) {
            actualizarCeldaEnemigo(disparo);
            JOptionPane.showMessageDialog(this, "Resultado del disparo: " + disparo.getResultado());
        } else if (tableroAfectado == this.miTablero) {
            actualizarCeldaPropia(disparo);
        }
    }

    @Override
    public void onChange(PartidaModel model) {

        actualizarTimer(model.getSegundosRestantes(), model.getTurnoDe());

        if (model.getEstado() == EstadoPartida.FINALIZADA) {
            JOptionPane.showMessageDialog(this, "¡Partida terminada! Ganador: " + model.getTurnoDe());

        }
    }

    public GameMediator getMediator() {
        return mediator;
    }

    public void setMediator(GameMediator mediator) {
        this.mediator = mediator;
    }

    public void setTableros(TableroModel miTablero, TableroModel tableroEnemigo) {
        this.miTablero = miTablero;
        this.tableroEnemigo = tableroEnemigo;

        mostrarTableroPropio(miTablero);
    }

}
