package com.itson.equipo2.battleship_cliente.view;

import com.itson.equipo2.battleship_cliente.models.CeldaModel;
import com.itson.equipo2.battleship_cliente.models.JugadorModel;
import com.itson.equipo2.battleship_cliente.models.PartidaModel;
import com.itson.equipo2.battleship_cliente.models.TableroModel;
import com.itson.equipo2.battleship_cliente.pattern.factory.ViewFactory;
import com.itson.equipo2.battleship_cliente.pattern.mediator.GameMediator;
import com.itson.equipo2.battleship_cliente.controllers.ViewController;
import com.itson.equipo2.battleship_cliente.pattern.observer.PartidaObserver;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import mx.itson.equipo_2.common.dto.CoordenadaDTO;
import mx.itson.equipo_2.common.dto.DisparoDTO;
import mx.itson.equipo_2.common.enums.EstadoCelda;
import mx.itson.equipo_2.common.enums.EstadoNave;
import mx.itson.equipo_2.common.enums.EstadoPartida;
import mx.itson.equipo_2.common.enums.ResultadoDisparo;
import static mx.itson.equipo_2.common.enums.ResultadoDisparo.IMPACTO_CON_HUNDIMIENTO;

/**
 *
 * @author Ariel Eduardo Borbon Izaguirre 00000252116 Sebastián Bórquez Huerta
 * 00000252115 Alberto Jiménez García 00000252595 José Eduardo Aguilar García
 * 00000252049 José Luis Islas Molina 00000252574
 */
public class DispararView extends javax.swing.JPanel implements ViewFactory, PartidaObserver {

    private JButton[][] botonesPropio = new JButton[10][10];
    private JButton[][] botonesEnemigo = new JButton[10][10];

    private CoordenadaDTO coordSeleccionada;
    private JButton ultimaSeleccionada;
    private JugadorModel jugador;
    private Timer timerNotificacion;
    private GameMediator mediator;

    private TableroModel miTablero;
    private TableroModel tableroEnemigo;

    private PartidaModel partidaModel; // refeerencia local

    public DispararView() {
        initComponents();
        crearCeldas();

    }

    public void setModels(PartidaModel partidaModel, TableroModel miTablero, TableroModel tableroEnemigo) {
        this.partidaModel = partidaModel;
        this.miTablero = miTablero;
        this.tableroEnemigo = tableroEnemigo;

        System.out.println("DispararView: Modelos inyectados.");
        actualizarLabelTurno();

//        mostrarTableroPropio(this.miTablero);
    

    //////////////////////////////////////////////////
    }
    
    
    
    @Override
    public void onChange(PartidaModel model) {
        System.out.println("Observer notificado: Repintando vista.");
        this.partidaModel = model;

        actualizarLabelTurno();
        actualizarLabelTimer(model.getSegundosRestantes());

        if (this.miTablero != null) {
            repintarPropio(this.miTablero, model.getYo().getColor().getColor());
        }
        if (this.tableroEnemigo != null) {
            repintarEnemigo(this.tableroEnemigo);
        }

        revalidate();
        repaint();

        if (model.getEstado() == EstadoPartida.FINALIZADA) {
            JOptionPane.showMessageDialog(this, "¡Partida terminada! Ganador: " + model.getTurnoDe());
            btnDisparar.setEnabled(false);
            btnRendirse.setEnabled(false);
        }

    }

    private void actualizarLabelTurno() {
        if (partidaModel == null || partidaModel.getTurnoDe() == null || partidaModel.getYo() == null) {
            lblTurno.setText("Cargando partida...");
            return;
        }

        boolean esMiTurno = partidaModel.getTurnoDe().equals(partidaModel.getYo().getId());

        if (esMiTurno) {
            lblTurno.setText("¡ES TU TURNO!");
            lblTurno.setForeground(Color.GREEN);
            btnDisparar.setEnabled(true);
        } else {
            lblTurno.setText("Turno del enemigo...");
            lblTurno.setForeground(Color.RED);
            btnDisparar.setEnabled(false);
        }
    }

    private void actualizarLabelTimer(Integer segundos) {
        if (segundos != null) {
            lblTimer.setText(segundos + "s");

            if (segundos <= 10) {
                lblTimer.setForeground(Color.ORANGE);
            } else {
                lblTimer.setForeground(Color.BLACK);
            }
        } else {
            lblTimer.setText(30 + "s");
            lblTimer.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTableroEnemigo = new JPanel();
        btnRendirse = new JButton();
        btnDisparar = new JButton();
        panelTableroPropio = new JPanel();
        lblTurno = new JLabel();
        lblTimer = new JLabel();
        btnMarcador = new JButton();
        lblResultado = new JLabel();

        setBackground(new Color(83, 111, 137));
        setMaximumSize(new Dimension(1280, 720));
        setMinimumSize(new Dimension(1280, 720));
        setPreferredSize(new Dimension(1280, 720));
        setLayout(null);

        panelTableroEnemigo.setBackground(new Color(82, 113, 177));
        panelTableroEnemigo.setMaximumSize(new Dimension(600, 600));
        panelTableroEnemigo.setMinimumSize(new Dimension(600, 600));
        panelTableroEnemigo.setLayout(new GridLayout(1, 0));
        panelTableroEnemigo.setLayout(new GridLayout(10, 10));
        add(panelTableroEnemigo);
        panelTableroEnemigo.setBounds(615, 56, 600, 600);

        btnRendirse.setBackground(new Color(75, 75, 75));
        btnRendirse.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRendirse.setForeground(new Color(255, 255, 255));
        btnRendirse.setText("RENDIRSE");
        btnRendirse.setBorder(null);
        btnRendirse.setFocusPainted(false);
        btnRendirse.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRendirseActionPerformed(evt);
            }
        });
        add(btnRendirse);
        btnRendirse.setBounds(60, 650, 156, 41);

        btnDisparar.setBackground(new Color(75, 75, 75));
        btnDisparar.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDisparar.setForeground(new Color(255, 255, 255));
        btnDisparar.setText("DISPARAR");
        btnDisparar.setBorder(null);
        btnDisparar.setFocusPainted(false);
        btnDisparar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnDispararActionPerformed(evt);
            }
        });
        add(btnDisparar);
        btnDisparar.setBounds(260, 650, 156, 41);

        panelTableroPropio.setBackground(new Color(82, 113, 177));
        panelTableroPropio.setMaximumSize(new Dimension(250, 250));
        panelTableroPropio.setMinimumSize(new Dimension(250, 250));
        panelTableroPropio.setLayout(new GridLayout(10, 10));
        add(panelTableroPropio);
        panelTableroPropio.setBounds(130, 50, 250, 250);

        lblTurno.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        lblTurno.setHorizontalAlignment(SwingConstants.CENTER);
        lblTurno.setText(" ");
        add(lblTurno);
        lblTurno.setBounds(80, 320, 360, 50);

        lblTimer.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        lblTimer.setHorizontalAlignment(SwingConstants.CENTER);
        lblTimer.setText(" ");
        add(lblTimer);
        lblTimer.setBounds(130, 400, 250, 30);

        btnMarcador.setBackground(new Color(75, 75, 75));
        btnMarcador.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        btnMarcador.setForeground(new Color(255, 255, 255));
        btnMarcador.setText("MARCADOR");
        btnMarcador.setBorder(null);
        btnMarcador.setFocusPainted(false);
        btnMarcador.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMarcadorActionPerformed(evt);
            }
        });
        add(btnMarcador);
        btnMarcador.setBounds(180, 480, 156, 41);

        lblResultado.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        lblResultado.setHorizontalAlignment(SwingConstants.CENTER);
        lblResultado.setText(" ");
        add(lblResultado);
        lblResultado.setBounds(100, 550, 330, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRendirseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRendirseActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas rendirte?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            System.out.println("El jugador se rindió");
        }
    }//GEN-LAST:event_btnRendirseActionPerformed

    private void btnDispararActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDispararActionPerformed
        if (coordSeleccionada == null) {
            mostrarError("Debes seleccionar una casilla para disparar.");
            return;
        }
        if (mediator != null) {
            mediator.disparar(coordSeleccionada.getColumna(), coordSeleccionada.getFila());
            System.out.println("1");
        }

        this.coordSeleccionada = null;

        if (this.ultimaSeleccionada != null) {
            // Restaurar el borde original (negro)
            this.ultimaSeleccionada.setBorder(new LineBorder(Color.BLACK, 1));
            this.ultimaSeleccionada = null;
        }


    }//GEN-LAST:event_btnDispararActionPerformed

    private void btnMarcadorActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMarcadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnDisparar;
    private JButton btnMarcador;
    private JButton btnRendirse;
    private JLabel lblResultado;
    private JLabel lblTimer;
    private JLabel lblTurno;
    private JPanel panelTableroEnemigo;
    private JPanel panelTableroPropio;
    // End of variables declaration//GEN-END:variables

    private void crearCeldas() {
        botonesEnemigo = new JButton[10][10];
        botonesPropio = new JButton[10][10];

        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {

                JButton celdaEnemigo = new JButton();
                celdaEnemigo.setBackground(new Color(50, 70, 100));
                celdaEnemigo.setBorder(new LineBorder(Color.BLACK, 1));

                final int f = fila;
                final int c = col;

                celdaEnemigo.addActionListener(e -> {

                    if (tableroEnemigo != null) {
                        CeldaModel celdaModelo = tableroEnemigo.getCelda(f, c);
                        if (celdaModelo != null && celdaModelo.getEstado() == EstadoCelda.DISPARADA) {
                            mostrarError("Ya has disparado en esta casilla.");
                            return; // No permitir seleccionar
                        }
                    }

                    if (ultimaSeleccionada != null) {
                        ultimaSeleccionada.setBorder(new LineBorder(Color.BLACK, 1));
                    }

                    ultimaSeleccionada = celdaEnemigo;

                    celdaEnemigo.setBorder(new LineBorder(Color.GRAY, 3));

                    coordSeleccionada = new CoordenadaDTO(f, c);
                });

                panelTableroEnemigo.add(celdaEnemigo);
                botonesEnemigo[fila][col] = celdaEnemigo;

                JButton celdaPropio = new JButton();
                //celdaPropio.setEnabled(false);
                celdaPropio.setBackground(new Color(50, 70, 100));
                celdaPropio.setBorder(new LineBorder(Color.BLACK, 1));

                panelTableroPropio.add(celdaPropio);
                botonesPropio[fila][col] = celdaPropio;
            }
        }
    }

    @Override
    public JPanel crear(ViewController control) {
        return this;
    }

    public void mostrarTableroPropio(TableroModel tablero) {
        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {
                CeldaModel celda = tablero.getCelda(fila, col);

                if (celda.tieneNave()) {
                    botonesPropio[fila][col].setBackground(Color.DARK_GRAY);
                }
            }
        }
    }

    public void actualizarTimer(int segundosRestantes, String jugador) {
        lblTurno.setText("Turno de " + jugador + " - Tiempo: " + segundosRestantes + "s");
    }

    public void setJugador(JugadorModel jugador) {
        this.jugador = jugador;
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.WARNING_MESSAGE);
    }

    public GameMediator getMediator() {
        return mediator;
    }

    public void setMediator(GameMediator mediator) {
        this.mediator = mediator;
    }

    public void setTableros(TableroModel miTablero, TableroModel tableroEnemigo) {
        this.miTablero = miTablero;
        this.tableroEnemigo = tableroEnemigo;

        mostrarTableroPropio(miTablero);
    }

    public void mostrarNotificacion(ResultadoDisparo resultado) {
        Color color;

        switch (resultado) {
            case AGUA ->
                color = Color.CYAN;

            case IMPACTO_SIN_HUNDIMIENTO ->
                color = Color.ORANGE;

            case IMPACTO_CON_HUNDIMIENTO ->
                color = Color.RED;
            default ->
                throw new AssertionError();
        }
        lblResultado.setText(resultado.getMensaje());
        lblResultado.setForeground(color);
//        lblResultado.setBackground(colorFondo);
        lblResultado.setVisible(true);

        if (timerNotificacion != null && timerNotificacion.isRunning()) {
            timerNotificacion.stop();
        }

        timerNotificacion = new javax.swing.Timer(2000, e -> {
            lblResultado.setText("");
            lblResultado.setBackground(new Color(0, 0, 0, 0));
            lblResultado.setVisible(false);
        });

        timerNotificacion.setRepeats(false);
        timerNotificacion.start();
    }

    public JLabel getLblResultado() {
        return lblResultado;
    }

    public void setLblResultado(JLabel lblResultado) {
        this.lblResultado = lblResultado;
    }

    private void repintarPropio(TableroModel tablero, Color color) {
        if (tablero == null) {
            return; // Seguridad
        }
        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {

                CeldaModel celda = tablero.getCelda(fila, col);
                JButton boton = botonesPropio[fila][col];

                // 1. Si la celda YA FUE DISPARADA (por el enemigo)
                if (celda.getEstado() == EstadoCelda.DISPARADA) {
                    if (celda.tieneNave()) {
                        // ¡Nos dieron!
                        boton.setBackground(Color.RED);
                    } else {
                        // Dispararon agua
                        boton.setBackground(Color.CYAN);
                    }
                } // 2. Si NO ha sido disparada, PERO tiene nave
                else if (celda.tieneNave()) {
                    boton.setBackground(color); // Muestra tu nave intacta
                } // 3. Si es solo agua (sin disparar y sin nave)
                else {
                    boton.setBackground(new Color(50, 70, 100)); // Color base del mar
                }
            }
        }
    }

    public void repintarEnemigo(TableroModel tablero) {
        if (tablero == null) {
            return;
        }

        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {

                CeldaModel celda = tablero.getCelda(fila, col);
                JButton boton = botonesEnemigo[fila][col];

                // 1. Si NO ha sido disparada, es "Niebla de Guerra"
                if (celda.getEstado() == EstadoCelda.NO_DISPARADA) {
                    boton.setBackground(new Color(50, 70, 100)); // Mar oculto
                    boton.setEnabled(true);
                    continue; // Siguiente celda
                }

                // 2. Si SÍ fue disparada, leemos el ESTADO DE LA NAVE
                EstadoNave estadoNave = celda.getEstadoNave();
                boton.setEnabled(false);

                // 3. Decidimos el color
                if (estadoNave == null) {
                    // Si el estadoNave es null, significa que fue AGUA
                    boton.setBackground(Color.BLUE);
                } else {
                    // Si el estadoNave NO es null, fue un impacto
                    switch (estadoNave) {
                        case AVERIADO:
                            boton.setBackground(Color.ORANGE); // Naranja para impacto
                            break;
                        case HUNDIDO:
                            boton.setBackground(Color.RED); // Rojo para hundido
                            break;
                        default:
                            boton.setBackground(Color.PINK); // Error
                    }
                }
            }
        }
    }
}
