/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itson.equipo2.battleship_cliente.view;

import com.itson.equipo2.battleship_cliente.controllers.ViewController;
import com.itson.equipo2.battleship_cliente.pattern.factory.ViewFactory;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author skyro
 */
public class EsperandoPosicionamientoVista extends javax.swing.JPanel implements ViewFactory {

    /**
     * Creates new form PosicionarNaveVista
     */
    public EsperandoPosicionamientoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();

        setBackground(new Color(83, 111, 137));
        setMaximumSize(new Dimension(1280, 720));
        setMinimumSize(new Dimension(1280, 720));
        setPreferredSize(new Dimension(1280, 720));
        setLayout(null);

        btnConfirmar.setBackground(new Color(75, 75, 75));
        btnConfirmar.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        btnConfirmar.setForeground(new Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorder(null);
        btnConfirmar.setEnabled(false);
        btnConfirmar.setFocusPainted(false);
        btnConfirmar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        add(btnConfirmar);
        btnConfirmar.setBounds(40, 640, 156, 41);

        jLabel1.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Esperando al rival...");
        jLabel1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setHorizontalTextPosition(SwingConstants.CENTER);
        add(jLabel1);
        jLabel1.setBounds(320, 510, 600, 50);

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/image/cargando.gif"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(380, 40, 480, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

    }//GEN-LAST:event_btnConfirmarActionPerformed

    @Override
    public JPanel crear(ViewController control) {
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnConfirmar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
