/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itson.equipo2.battleship_cliente.view;

import com.itson.equipo2.battleship_cliente.controllers.PosicionarController;
import com.itson.equipo2.battleship_cliente.controllers.ViewController;
import com.itson.equipo2.battleship_cliente.models.CeldaModel;
import com.itson.equipo2.battleship_cliente.models.PartidaModel;
import com.itson.equipo2.battleship_cliente.models.TableroModel;
import com.itson.equipo2.battleship_cliente.pattern.factory.ViewFactory;
import com.itson.equipo2.battleship_cliente.pattern.observer.PartidaObserver;
import com.itson.equipo2.battleship_cliente.view.util.NaveView;
import com.itson.equipo2.battleship_cliente.view.util.SelectorNaveView;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.border.LineBorder;
import mx.itson.equipo_2.common.enums.TipoNave;

/**
 *
 * @author skyro
 */
public class PosicionarNaveVista extends javax.swing.JPanel implements ViewFactory, PartidaObserver {

    private List<NaveView> navesEnTablero = new java.util.ArrayList<>();

    private PosicionarController posicionarController;

    /**
     * Creates new form PosicionarNaveVista
     */
    public PosicionarNaveVista(PosicionarController posicionarController) {
        this.posicionarController = posicionarController;
        initComponents();
        crearCeldas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero = new JPanel();
        btnConfirmar = new JButton();
        nave1 = new SelectorNaveView(TipoNave.BARCO, this.tablero, this.posicionarController);
        nave2 = new SelectorNaveView(TipoNave.SUBMARINO, this.tablero, this.posicionarController);
        nave3 = new SelectorNaveView(TipoNave.CRUCERO, this.tablero, this.posicionarController);
        nave4 = new SelectorNaveView(TipoNave.PORTA_AVIONES, this.tablero, this.posicionarController);

        setBackground(new Color(83, 111, 137));
        setMaximumSize(new Dimension(1280, 720));
        setMinimumSize(new Dimension(1280, 720));
        setPreferredSize(new Dimension(1280, 720));

        tablero.setBackground(new Color(82, 113, 177));
        tablero.setMaximumSize(new Dimension(570, 570));
        tablero.setMinimumSize(new Dimension(570, 570));
        tablero.setPreferredSize(new Dimension(570, 570));
        tablero.setLayout(new GridLayout(10, 10));

        btnConfirmar.setBackground(new Color(75, 75, 75));
        btnConfirmar.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        btnConfirmar.setForeground(new Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorder(null);
        btnConfirmar.setEnabled(false);
        btnConfirmar.setFocusPainted(false);
        btnConfirmar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        nave1.setMaximumSize(new Dimension(57, 57));
        nave1.setMinimumSize(new Dimension(57, 57));
        nave1.setName(""); // NOI18N
        nave1.setPreferredSize(new Dimension(57, 57));

        GroupLayout nave1Layout = new GroupLayout(nave1);
        nave1.setLayout(nave1Layout);
        nave1Layout.setHorizontalGroup(nave1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        nave1Layout.setVerticalGroup(nave1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        nave2.setMaximumSize(new Dimension(114, 57));
        nave2.setMinimumSize(new Dimension(114, 57));
        nave2.setName(""); // NOI18N
        nave2.setPreferredSize(new Dimension(114, 57));

        GroupLayout nave2Layout = new GroupLayout(nave2);
        nave2.setLayout(nave2Layout);
        nave2Layout.setHorizontalGroup(nave2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        nave2Layout.setVerticalGroup(nave2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        nave3.setMaximumSize(new Dimension(171, 57));
        nave3.setMinimumSize(new Dimension(171, 57));
        nave3.setName(""); // NOI18N
        nave3.setPreferredSize(new Dimension(171, 57));
        nave3.setRequestFocusEnabled(false);

        GroupLayout nave3Layout = new GroupLayout(nave3);
        nave3.setLayout(nave3Layout);
        nave3Layout.setHorizontalGroup(nave3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        nave3Layout.setVerticalGroup(nave3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        nave4.setMaximumSize(new Dimension(228, 57));
        nave4.setMinimumSize(new Dimension(228, 57));
        nave4.setName(""); // NOI18N
        nave4.setPreferredSize(new Dimension(228, 57));
        nave4.setRequestFocusEnabled(false);

        GroupLayout nave4Layout = new GroupLayout(nave4);
        nave4.setLayout(nave4Layout);
        nave4Layout.setHorizontalGroup(nave4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        nave4Layout.setVerticalGroup(nave4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1080, 1080, 1080)
                .addComponent(btnConfirmar, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tablero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nave4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nave3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nave2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nave1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(tablero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(nave1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(nave2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nave3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(nave4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)))
                .addComponent(btnConfirmar, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
        );

        nave1.getAccessibleContext().setAccessibleName("");
        nave1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        posicionarController.confirmarPosicionamiento();

        // Deshabilita todo para que no pueda mover nada más
        btnConfirmar.setEnabled(false);
        nave1.setEnabled(false);
        nave2.setEnabled(false);
        nave3.setEnabled(false);
        nave4.setEnabled(false);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    @Override
    public JPanel crear(ViewController control) {
        return this;
    }

    @Override
    public void onChange(PartidaModel model) {
        // Obtiene el tablero del modelo
        TableroModel tableroPropio = model.getTableroPropio(); //
        if (tableroPropio == null) {
            System.out.println("tablero nulo");
            return;
        }

        // Recorre las celdas de la VISTA
        for (int f = 0; f < 10; f++) {
            for (int c = 0; c < 10; c++) {
                // Obtiene el estado del MODELO
                CeldaModel celdaModelo = tableroPropio.getCelda(f, c); //

                // Obtiene el componente de la VISTA
                JButton celdaUI = (JButton) tablero.getComponent(f * 10 + c);

                // Sincroniza la Vista con el Modelo
                if (celdaModelo.tieneNave()) {
                    System.out.println("hay nave!");
                    celdaUI.setBackground(model.getYo().getColor().getColor()); // O el color que prefieras
                } else {
                    celdaUI.setBackground(new Color(50, 70, 100)); // Color agua
                }
            }
        }
        
        actualizarEstadoBoton();
    }

    private void crearCeldas() {

        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {

                JButton celdaPropio = new JButton();
                celdaPropio.setEnabled(false);
                celdaPropio.setBackground(new Color(50, 70, 100));
                celdaPropio.setBorder(new LineBorder(Color.BLACK, 1));

                tablero.add(celdaPropio);
            }
        }
    }

    public void actualizarEstadoBoton() {

        // ¡El truco! Hacemos un "cast" al JPanel genérico
        // para tratarlo como lo que realmente es: un SelectorNaveView.
        boolean todosPuestos
                = ((SelectorNaveView) nave1).getBarcosRestantes() == 0
                && ((SelectorNaveView) nave2).getBarcosRestantes() == 0
                && ((SelectorNaveView) nave3).getBarcosRestantes() == 0
                && ((SelectorNaveView) nave4).getBarcosRestantes() == 0;
        // (Añade '&& ((SelectorNaveView) nave5).getBarcosRestantes() == 0' si tienes una quinta nave)

        btnConfirmar.setEnabled(todosPuestos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnConfirmar;
    private JPanel nave1;
    private JPanel nave2;
    private JPanel nave3;
    private JPanel nave4;
    private JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
