/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itson.equipo2.battleship_cliente.view;

import com.itson.equipo2.battleship_cliente.controllers.SalaController;
import com.itson.equipo2.battleship_cliente.controllers.VistaController;
import com.itson.equipo2.battleship_cliente.models.PartidaModel;
import com.itson.equipo2.communication.dto.EventMessage;
import java.awt.BorderLayout;
import java.awt.Image;
import java.net.InetAddress;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import mx.itson.equipo_2.common.broker.BrokerConfig;
import com.itson.equipo2.battleship_cliente.pattern.factory.VistaFactory;
import com.itson.equipo2.battleship_cliente.pattern.observer.IObserver;

/**
 *
 * @author PC Gamer
 */
public class SalaPartidaView extends javax.swing.JPanel implements VistaFactory, IObserver<PartidaModel> {

    private final SalaController salaController;
    
    private final JLabel lblIconoJugador1 = new JLabel();
    private final JLabel lblIconoJugador2 = new JLabel();
    
    private ImageIcon iconUser;
    private ImageIcon iconWifi;

    public SalaPartidaView(SalaController salaController) {
        this.salaController = salaController;
        initComponents();

        cargarIconos();
        
        configurarPanelesIconos();
        
        mostrarIpLocal();
        btnConfirmar.setEnabled(false);
    }

    private void mostrarIpLocal() {
        try {
            String ip = InetAddress.getLocalHost().getHostAddress();
            lblIp.setText("IP de Sala: " + ip);
        } catch (Exception e) {
            lblIp.setText("IP: Desconocida");
        }
    }



    @Override
    public JPanel crear(VistaController control) {
        return this;
    }

    @Override
    public void onChange(PartidaModel model) {
        if (model.getNombreJugador1() != null) {
            lblJugador1.setText(model.getNombreJugador1());
        }
        if (model.getNombreJugador2() != null) {
            lblJugador2.setText(model.getNombreJugador2());
        }


        lblIconoJugador1.setIcon(iconUser);

        String nombreJ2 = model.getNombreJugador2();
        boolean hayRival = nombreJ2 != null && !nombreJ2.equals("Esperando...");

        if (hayRival) {
            lblIconoJugador2.setIcon(iconUser);
        } else {
            lblIconoJugador2.setIcon(iconWifi);
        }

        if (model.isSoyHost()) {
            if (hayRival) {
                btnConfirmar.setEnabled(true);
                btnConfirmar.setText("INICIAR JUEGO");
            } else {
                btnConfirmar.setEnabled(false);
                btnConfirmar.setText("Esperando rival...");
            }
        } else {
            btnConfirmar.setEnabled(false);
            btnConfirmar.setText("Esperando al Host...");
        }

        this.revalidate();
        this.repaint();
    }
    
    private void cargarIconos() {
        try {

            ImageIcon originalUser = new ImageIcon(getClass().getResource("/images/user_icon.png"));
            Image imgUser = originalUser.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            this.iconUser = new ImageIcon(imgUser);

            
            ImageIcon originalWifi = new ImageIcon(getClass().getResource("/images/wifi_icon.png"));
            Image imgWifi = originalWifi.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            this.iconWifi = new ImageIcon(imgWifi);

        } catch (Exception e) {
            System.err.println("Error al cargar iconos en SalaPartidaView: " + e.getMessage());
        }
    }
    
    private void configurarPanelesIconos() {
        lblIconoJugador1.setHorizontalAlignment(JLabel.CENTER);
        pnlUserIcon.removeAll();
        pnlUserIcon.add(lblIconoJugador1, BorderLayout.CENTER);

        lblIconoJugador2.setHorizontalAlignment(JLabel.CENTER);
        jPanel2.removeAll();
        jPanel2.add(lblIconoJugador2, BorderLayout.CENTER);
        
        pnlUserIcon.revalidate();
        jPanel2.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        pnlUserIcon = new javax.swing.JPanel();
        lblJugador2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(83, 111, 137));

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        lblTitulo.setText("Sala Partida");

        lblJugador1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador1.setText("Nombre1");
        lblJugador1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVolver.setBackground(new java.awt.Color(0, 102, 204));
        btnVolver.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("< Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(0, 153, 51));
        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        pnlUserIcon.setBackground(new java.awt.Color(83, 111, 137));
        pnlUserIcon.setLayout(new java.awt.BorderLayout());

        lblJugador2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador2.setText("Nombre2");

        jPanel2.setBackground(new java.awt.Color(83, 111, 137));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lblIp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIp.setText("IP: ....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(pnlUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIp, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblIp)
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJugador1)
                            .addComponent(lblJugador2)))
                    .addComponent(lblTitulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        salaController.volverAlLobby();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
       salaController.iniciarJuego();
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlUserIcon;
    // End of variables declaration//GEN-END:variables
}
