/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itson.equipo2.battleship_cliente.view;

import com.itson.equipo2.battleship_cliente.controllers.VistaController;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PC Gamer
 */
public class VictoriaView extends javax.swing.JPanel {

    private final VistaController viewController; 

    /**
     * Creates new form VictoriaView
     * @param viewController
     */
    public VictoriaView(VistaController viewController) {
        this.viewController = viewController;
        initComponents();

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/victoria_img.png"));
            JLabel lblImagen = new JLabel(icon);
            pnlVictory.add(lblImagen, java.awt.BorderLayout.CENTER);
        } catch (Exception e) {
            System.err.println("Error cargando imagen victoria: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVictory = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();

        setBackground(new java.awt.Color(83, 111, 137));

        pnlVictory.setBackground(new java.awt.Color(83, 111, 137));
        pnlVictory.setLayout(new java.awt.BorderLayout());

        btnContinuar.setBackground(new java.awt.Color(0, 204, 204));
        btnContinuar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(pnlVictory, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(pnlVictory, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnContinuar)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        viewController.cambiarPantalla("lobby");
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel pnlVictory;
    // End of variables declaration//GEN-END:variables
}
